separator = "=>"

palette.visible = true

[box]
visible = true
title = "NixOS"
border = "rounded"

key_color = "#@keyColor@"
separator_color = "#@separatorColor@"

[custom_ascii]
color = "#@asciiColor@"
path = "./NixLogo.txt"
