separator = "=>"

palette.visible = true

[box]
visible = true
title = "NixOS"
border = "rounded"

key_color = "#81A1C1"
separator_color = "#D08770"

[custom_ascii]
path = "./NixLogo.txt"
color = "#D8DEE9"
